/**
 * DATOS DE POKÉMON PARA ADIVINA QUIÉN
 * 
 * Cada Pokémon tiene características booleanas que serán usadas
 * para las preguntas del juego. El servidor valida respuestas SI/NO
 * basándose en estas propiedades.
 *
 * Usamos imágenes oficiales de PokeAPI
 */

const POKEMONS = [
  {
    id: 1, name: "Bulbasaur",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
    tipo: "planta",
    esAgua: false, esFuego: false, esPlanta: true, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: true,
    tieneCuernos: true, tieneAlas: false, tieneCola: false, esCuadrupedo: true, esLegendario: false,
    esVerde: true, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 4, name: "Charmander",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
    tipo: "fuego",
    esAgua: false, esFuego: true, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: true, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 7, name: "Squirtle",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
    tipo: "agua",
    esAgua: true, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 10, name: "Caterpie",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png",
    tipo: "bicho",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: true, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: true, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 13, name: "Weedle",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png",
    tipo: "bicho",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: true, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: true,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: true,
  },
  {
    id: 16, name: "Pidgey",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png",
    tipo: "normal",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: true, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: true, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: true, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: true,
  },
  {
    id: 23, name: "Ekans",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png",
    tipo: "veneno",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: true,
    tieneCuernos: false, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: true, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 25, name: "Pikachu",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    tipo: "electrico",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: true, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: false, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: true, esAzul: false, esMorado: false, esNegro: false, esBlanco: false,
  },
  {
    id: 27, name: "Sandshrew",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png",
    tipo: "tierra",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: true, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: true, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 35, name: "Clefairy",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png",
    tipo: "hada",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: true, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: true, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: true, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: true, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 39, name: "Jigglypuff",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png",
    tipo: "normal",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: true, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: true, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: true, esNegro: false, esBlanco: false,
  },
  {
    id: 43, name: "Oddish",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png",
    tipo: "planta",
    esAgua: false, esFuego: false, esPlanta: true, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: true,
    tieneCuernos: false, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 52, name: "Meowth",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png",
    tipo: "normal",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: true, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false,	esRojo: false,	esAmarillo: false,	esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: true,
  },
  {
    id: 54, name: "Psyduck",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png",
    tipo: "agua",
    esAgua: true, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false,	esRojo: false,	esAmarillo: true,	esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 56, name: "Mankey",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png",
    tipo: "lucha",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: true, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: true,
  },
  {
    id: 58, name: "Growlithe",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png",
    tipo: "fuego",
    esAgua: false, esFuego: true, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: true, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: true, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 63, name: "Abra",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png",
    tipo: "psiquico",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: true, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: true, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 66, name: "Machop",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png",
    tipo: "lucha",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: true, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 74, name: "Geodude",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png",
    tipo: "roca",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: true, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: true, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: true, esBlanco: false, esCafe: true,
  },
  {
    id: 79, name: "Slowpoke",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png",
    tipo: "agua",
    esAgua: true, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: true, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: true, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 81, name: "Magnemite",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png",
    tipo: "electrico",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: true, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: true, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 92, name: "Gastly",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png",
    tipo: "fantasma",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: true, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: true,
    tieneCuernos: false, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: true, esBlanco: false, esCafe: false,
  },
  {
    id: 94, name: "Gengar",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png",
    tipo: "fantasma",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: true, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: true,
    tieneCuernos: false, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false,
  },
  {
    id: 95, name: "Onix",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png",
    tipo: "roca",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: true, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: true, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: true, esBlanco: false, esCafe: false,
  },
  {
    id: 106, name: "Hitmonlee",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png",
    tipo: "lucha",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: true, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: true,
  },
  {
    id: 111, name: "Rhyhorn",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png",
    tipo: "tierra",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: true, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: true, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: false, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: true, esBlanco: false, esCafe: false,
  },
  {
    id: 113, name: "Chansey",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png",
    tipo: "normal",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: true, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: true, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 129, name: "Magikarp",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png",
    tipo: "agua",
    esAgua: true, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: true, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 131, name: "Lapras",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png",
    tipo: "agua",
    esAgua: true, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: true, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 132, name: "Ditto",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png",
    tipo: "normal",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: true, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: false, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: true, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 133, name: "Eevee",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png",
    tipo: "normal",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: true, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: true,
  },
  {
    id: 134, name: "Vaporeon",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png",
    tipo: "agua",
    esAgua: true, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 135, name: "Jolteon",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png",
    tipo: "electrico",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: true, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: true, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 136, name: "Flareon",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png",
    tipo: "fuego",
    esAgua: false, esFuego: true, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false, esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: true, esLegendario: false,
    esVerde: false, esRojo: true, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 143, name: "Snorlax",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png",
    tipo: "normal",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: true, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: false, esCuadrupedo: false, esLegendario: false,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 144, name: "Articuno",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png",
    tipo: "hielo",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: true, esLucha: false, esVolador: true, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: true, tieneAlas: true, tieneCola: true, esCuadrupedo: false, esLegendario: true,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: true, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 145, name: "Zapdos",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png",
    tipo: "electrico",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: true, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: true, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: false, tieneAlas: true, tieneCola: true, esCuadrupedo: false, esLegendario: true,
    esVerde: false, esRojo: false, esAmarillo: true, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 146, name: "Moltres",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png",
    tipo: "fuego",
    esAgua: false, esFuego: true, esPlanta: false, esElectrico: false, esPsiquico: false, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: true, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: false, tieneAlas: true, tieneCola: true, esCuadrupedo: false, esLegendario: true,
    esVerde: false, esRojo: true, esAmarillo: false, esAzul: false, esMorado: false, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 150, name: "Mewtwo",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png",
    tipo: "psiquico",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: true, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: true,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: true, esNegro: false, esBlanco: false, esCafe: false,
  },
  {
    id: 151, name: "Mew",
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png",
    tipo: "psiquico",
    esAgua: false, esFuego: false, esPlanta: false, esElectrico: false, esPsiquico: true, esNormal: false, esFantasma: false, 
    esHielo: false, esLucha: false, esVolador: false, esBicho: false, esRoca: false, esSiniestro: false, esAcero: false, 
    esHada: false, esDragon: false, esTierra: false,	esVeneno: false,
    tieneCuernos: true, tieneAlas: false, tieneCola: true, esCuadrupedo: false, esLegendario: true,
    esVerde: false, esRojo: false, esAmarillo: false, esAzul: false, esMorado: true, esNegro: false, esBlanco: false, esCafe: false,
  },
];

const PREGUNTAS = [
  { id: "esAgua",            texto: "¿Es de tipo Agua?" },
  { id: "esFuego",           texto: "¿Es de tipo Fuego?" },
  { id: "esPlanta",          texto: "¿Es de tipo Planta?" },
  { id: "esElectrico",       texto: "¿Es de tipo Eléctrico?" },
  { id: "esPsiquico",        texto: "¿Es de tipo Psíquico?" },
  { id: "esNormal",          texto: "¿Es de tipo Normal?" },
  { id: "esFantasma",        texto: "¿Es de tipo Fantasma?" },
  { id: "esHielo",           texto: "¿Es de tipo Hielo?" },
  { id: "esLucha",           texto: "¿Es de tipo Lucha?" },
  { id: "esVolador",         texto: "¿Es de tipo Volador?" }, 
  { id: "esBicho",           texto: "¿Es de tipo Bicho?" },
  { id: "esRoca",            texto: "¿Es de tipo Roca?" },
  { id: "esSiniestro",       texto: "¿Es de tipo Siniestro?" },
  { id: "esAcero",           texto: "¿Es de tipo Acero?" },
  { id: "esHada",            texto: "¿Es de tipo Hada?" },
  { id: "esDragon",          texto: "¿Es de tipo Dragón?" },
  { id: "esTierra",          texto: "¿Es de tipo Tierra?" },
  { id: "esVeneno",          texto: "¿Es de tipo Veneno?" },
  { id: "tieneCuernos",      texto: "¿Tiene cuernos, orejas o protuberancias en la cabeza?" },
  { id: "tieneAlas",         texto: "¿Tiene alas?" },
  { id: "tieneCola",        texto: "¿Tiene cola?" },
  { id: "esCuadrupedo",      texto: "¿Camina en cuatro patas?" },
  { id: "esLegendario",      texto: "¿Es un Pokémon legendario?" },
  { id: "esVerde",           texto: "¿Es predominantemente verde?" },
  { id: "esRojo",            texto: "¿Es predominantemente rojo o naranja?" },
  { id: "esAmarillo",        texto: "¿Es predominantemente amarillo?" },
  { id: "esAzul",            texto: "¿Es predominantemente azul?" },
  { id: "esMorado",          texto: "¿Es predominantemente morado o rosado?" },
  { id: "esNegro",           texto: "¿Es predominantemente negro o gris?" },
  { id: "esBlanco",          texto: "¿Es predominantemente blanco?" },
  { id: "esCafe",            texto: "¿Es predominantemente café?" },
];

module.exports = { POKEMONS, PREGUNTAS };
